name: Quality Assurance

on:
  workflow_dispatch:
  pull_request:
    branches: [master, dev]
  push:
    branches: [dev]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn lint:tsc
      - run: yarn lint:eslint
      - run: yarn lint:scss
      - run: yarn lint:commit

  audit:
    name: Run Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn npm audit --severity moderate
